const L=[
["Introduction to Construction","Understand project stages and the Quantity Surveyor's role.",`Construction converts a design into a physical asset. A typical project passes through concept/feasibility, design, estimating and tendering, procurement, construction, handover and close-out. A QS supports measurement and commercial control by reading drawings, measuring work, preparing BOQs and estimates, checking bills, tracking variations and monitoring cost.`,`A house project starts with drawings and specifications. The QS uses them to measure excavation, concrete, reinforcement, masonry, finishes and other work.`,`List five visible elements of a nearby building and decide whether each is naturally measured by length, area, volume, number or weight.`,`Which document primarily shows dimensions and geometry?`,["Drawings","Payroll","Attendance"],0,`Draw a project flow from Concept → Design → Estimate/Tender → Construction → Handover and add a QS activity at each relevant stage.`],
["Building Components","Identify major substructure and superstructure components.",`A building can be considered as substructure and superstructure. Important components include foundations, plinth, columns, beams, slabs, walls, doors/windows, stairs, roof, finishes and services. Structural loads must ultimately be transferred safely to the ground.`,`In an RCC frame, loads commonly travel from slab to beams, columns, foundations and then soil.`,`Sketch a two-storey building and label foundation, column, beam, slab, wall, stair and roof.`,`Which component transfers structural loads to the ground?`,["Paint","Foundation","Window"],1,`Create a table of 10 building components, their purpose and a likely measurement unit.`],
["Construction Materials","Recognize common materials and their measurement basis.",`Common materials include cement, aggregates, concrete, reinforcement steel, bricks/blocks, timber, glass, tiles and finishing products. A QS needs material awareness because specifications, quantities, wastage and unit rates affect cost.`,`Concrete is commonly measured by volume, reinforcement by weight, and floor tiles by area.`,`Identify five materials in your building and note their function and measurement basis.`,`Which unit type suits concrete volume?`,["m³","m²","number"],0,`Make a 12-item material register with use and typical measurement unit.`],
["Foundation Basics","Understand foundation purpose and broad categories.",`Foundations transfer loads safely to supporting soil or rock. Selection depends on loads, ground conditions, groundwater and engineering design. Broad categories include shallow foundations such as isolated, combined and raft foundations, and deep foundations such as piles.`,`A small framed building on suitable soil may use isolated footings; other conditions may require another engineered solution.`,`Draw an isolated footing and label excavation, footing and column/pedestal.`,`Primary purpose of a foundation?`,["Decoration","Transfer loads safely to ground","Painting"],1,`Compare isolated footing, raft and pile foundation in a table.`],
["RCC Fundamentals","Understand concrete, reinforcement and QS measurement.",`RCC means reinforced cement concrete. Concrete performs well in compression and reinforcement is incorporated to meet structural requirements including tensile resistance. QS measurement can separate concrete volume, reinforcement weight and formwork area.`,`For a column, concrete may be m³, steel kg/tonnes and formwork m².`,`Calculate concrete volume for a 0.30 m × 0.45 m × 3.0 m column.`,`Volume of that column?`,["0.405 m³","4.05 m³","0.045 m³"],0,`Calculate concrete volume for four 0.30 m × 0.30 m × 3 m columns.`],
["Brickwork & Masonry","Understand masonry and basic area measurement.",`Masonry uses units such as bricks or blocks bonded with mortar. QS work includes wall dimensions, thickness, openings, specification and applicable measurement rules.`,`A 5 m × 3 m wall has a gross face area of 15 m² before considering openings and project measurement rules.`,`Measure one room wall approximately and calculate gross area.`,`A 4 m × 3 m wall has gross area:`,["7 m²","12 m²","24 m²"],1,`Calculate gross wall areas for a 4 m × 3 m room with 3 m wall height.`],
["Flooring & Finishes","Identify common finishes and area measurement.",`Finishes protect surfaces and provide required appearance/performance. Examples include plaster, paint, tiles, stone flooring, skirting, ceilings and waterproofing. Project specifications and measurement rules control how work is quantified.`,`A 4 m × 5 m room has 20 m² gross floor area.`,`Calculate floor area and perimeter for a 3.5 m × 4.2 m room.`,`A 5 m × 4 m floor has area:`,["9 m²","20 m²","40 m²"],1,`Create a finish schedule for one room: floor, walls, ceiling, skirting and paint.`],
["Construction Sequence","Understand a typical logical building sequence.",`A simplified sequence is site setup, setting out, excavation, foundations, plinth, frame/walls, roof/slabs, services, finishes, fixtures, testing and handover. Real projects vary and activities can overlap.`,`Service rough-ins are coordinated before certain finishes close the work, reducing rework.`,`Order: painting, excavation, foundation, flooring, setting out.`,`Which normally comes before foundation work?`,["Excavation","Final painting","Handover"],0,`Draw a 12-step construction sequence for a small residence.`],
["Drawing & QS Terminology","Learn essential drawing and QS terms.",`A plan is a horizontal representation; an elevation shows a vertical face; a section cuts through the building. Dimensions, levels, grids, legends, notes and scales aid interpretation. QS terms include take-off, BOQ, item description, unit rate, estimate, variation, interim/RA bill and reconciliation.`,`A plan can show room dimensions while a section clarifies vertical relationships and layers.`,`On a simple house plan, identify title, scale, dimensions, notes and room labels.`,`Which view represents a cut through a building?`,["Section","Invoice","BOQ"],0,`Create a glossary of 20 construction/QS terms in your own words.`],
["Level 1 Review","Consolidate the fundamentals before drawing reading.",`You should now recognize project stages, building components, materials, foundation concepts, RCC, masonry, finishes, construction sequence and basic drawing/QS terminology. Level 2 will focus on Engineering Drawing Reading.`,`Before measuring a wall, a QS needs to know what it is, where dimensions come from, its specification and the applicable measurement rules.`,`Explain in five sentences how drawings become quantities and quantities become cost information.`,`What is Level 2?`,["Engineering Drawing Reading","Aircraft Maintenance","Graphic Design"],0,`Compile all Level 1 assignments into a workbook and add a one-page reflection on the QS role.`]
];
let S=JSON.parse(localStorage.getItem("esa_qs_l1")||'{"done":[],"cur":0}');
function save(){localStorage.setItem("esa_qs_l1",JSON.stringify(S));renderNav();let p=Math.round(S.done.length/L.length*100);pct.textContent=p+"%";bar.style.width=p+"%"}
function renderNav(){nav.innerHTML="";L.forEach((x,i)=>{let b=document.createElement("button");b.className="nav "+(i==S.cur?"on ":"")+(S.done.includes(i)?"done":"");b.textContent=(i+1)+". "+x[0];b.onclick=()=>openL(i);nav.appendChild(b)})}
function openL(i){S.cur=i;save();let x=L[i];content.innerHTML=`<small>LESSON ${i+1} OF 10</small><h2>${x[0]}</h2><div class="objective"><b>Learning objective</b><br>${x[1]}</div><p>${x[2]}</p><div class="box"><b>💡 REAL EXAMPLE</b><p>${x[3]}</p></div><div class="box"><b>🏗️ PRACTICAL TASK</b><p>${x[4]}</p></div><div class="box quiz"><b>❓ QUICK CHECK</b><p>${x[5]}</p>${x[6].map((a,j)=>`<button onclick="check(${j},${x[7]},this)">${a}</button>`).join("")}<div class="feedback"></div></div><div class="box"><b>📝 ASSIGNMENT</b><p>${x[8]}</p></div><button class="complete" onclick="done(${i})">${S.done.includes(i)?"✓ Completed":"Mark Lesson Complete"}</button>`}
function check(j,a,b){let f=b.parentElement.querySelector(".feedback");f.textContent=j==a?"✓ Correct.":"Review the lesson and try again.";f.style.color=j==a?"#65e1ee":"#f0b3b3"}
function done(i){if(!S.done.includes(i))S.done.push(i);save();openL(i)}
function assessment(){let qs=[["Concrete volume is generally measured in:",["m²","m³","number"],1],["A cut through a building is a:",["Section","Invoice","BOQ"],0],["Loads are transferred to ground by:",["Foundation","Paint","Door"],0],["BOQ means:",["Bill of Quantities","Base Office Quality","Building Order Quote"],0],["5 m × 4 m floor area:",["9 m²","20 m²","40 m²"],1]];content.innerHTML=`<small>LEVEL 1 FINAL CHECK</small><h2>Construction Fundamentals Assessment</h2>`+qs.map((q,i)=>`<div class="box"><b>Q${i+1}</b><p>${q[0]}</p>${q[1].map((a,j)=>`<label><input type=radio name=q${i} value=${j}> ${a}</label><br>`).join("")}</div>`).join("")+`<button class=complete onclick='grade(${JSON.stringify(qs.map(q=>q[2]))})'>Submit</button><div id=res></div>`}
function grade(k){let s=0;k.forEach((a,i)=>{let x=document.querySelector(`input[name=q${i}]:checked`);if(x&&+x.value==a)s++});res.innerHTML=`<p class=result>${s}/5</p><p>${s>=4?"Strong first-pass result. Complete the practical assignments before Level 2.":"Review weak areas and retake the assessment."}</p>`}
renderNav();openL(S.cur);save();